### What is a Random Number?
Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

### Pseudo Random and True Random.
Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.

If there is a program to generate random number it can be predicted, thus it is not truly random.

Random numbers generated through a generation algorithm are called pseudo random.

Can we make truly random numbers?

Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.

We do not need truly random numbers, unless its related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels).

In this tutorial we will be using pseudo random numbers.

### Generate Random Number
NumPy offers the random module to work with random numbers.

In [1]:
# Generate a random integer from 0 to 100:

from numpy import random
x = random.randint(100)
print(x)

51


### Generate Random Float
The random module's rand() method returns a random float between 0 and 1.

In [2]:
x = random.rand()
print(x)

0.046375647014880395


### Generate Random Array
In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.

### Integers
The randint() method takes a size parameter where you can specify the shape of an array.

In [4]:
# Generate a 1-D array containing 5 random integers from 0 to 100:
x = random.randint(100, size = (5))
print(x)

[ 8 20 11 98 44]


In [5]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:
x = random.randint(100, size = (3, 5))
print(x)

[[ 2  1 14 43 61]
 [32 54 33 22 28]
 [17 11  8 34 35]]


### Floats
The rand() method also allows you to specify the shape of the array.

In [6]:
# Generate a 1-D array containing 5 random floats:
x = random.rand(5)
print(x)

[0.86525804 0.85789216 0.62496905 0.85930675 0.78306506]


In [7]:
# Generate a 2-D array with 3 rows, each row containing 5 random numbers:
x = random.rand(3, 5)
print(x)

[[0.22395443 0.73469027 0.97132909 0.36148124 0.7842742 ]
 [0.12077001 0.95972451 0.31316941 0.24868459 0.78682502]
 [0.14510068 0.60239927 0.25373049 0.37009527 0.91912188]]


### Generate Random Number From Array
The choice() method allows you to generate a random value based on an array of values.

The choice() method takes an array as a parameter and randomly returns one of the values.

In [8]:
# Return one of the values in an array:

x = random.choice([3,5,7,0])
print(x)

5


The choice() method also allows you to return an array of values.

Add a size parameter to specify the shape of the array.

In [10]:
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):
x = random.choice([3,5,7,9], size = (3, 5))
print(x)

[[5 3 3 9 9]
 [5 3 5 3 5]
 [3 9 3 3 7]]
