### Sorting Arrays
Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [2]:
# Sort the array:

import numpy as np
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


Note: This method returns a copy of the array, leaving the original array unchanged.

You can also sort arrays of strings, or any other data type:

In [3]:
# Sort the array alphabetically:
arr = np.array(['cherry','apple','banana'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [4]:
# Sort a boolean array:

arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


### Sorting a 2-D Array
If you use the sort() method on a 2-D array, both arrays will be sorted:

In [5]:
arr = np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


### Filtering Arrays
Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [8]:
# Create an array from the elements on index 0 and 2:
arr = np.array([41,42,43,44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


The example above will return [41, 43], why?

Because the new array contains only the values where the filter array had the value True, in this case, index 0 and 2.

### Creating the Filter Array
In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.

In [17]:
# Create a filter array that will return only values higher than 42:
# Create an empty list
filter_arr = []

for x in arr:
    if x > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
        
newarr = arr[filter_arr]
print(newarr)

[43 44]


In [19]:
# Create a filter array that will return only even elements from the original array:
arr = np.array([1,2,3,4,5,6,7])

filter_list = []
for e in arr:
    # if the element is completely divisble by 2, set the value to True, otherwise False 
    if e % 2 == 0:
        filter_list.append(True)
    else:
        filter_list.append(False)
newarr = arr[filter_list]
print(newarr)

[2 4 6]


### Creating Filter Directly From Array
The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.

We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

In [21]:
# Create a filter array that will return only values higher than 42:
arr = np.array([41,42,43,44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(newarr)

[43 44]


In [22]:
# Create a filter array that will return only even elements from the original array:
arr = np.array([1,2,3,4,5,6,7])

filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(newarr)

[2 4 6]
