### Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [1]:
# Get the first element from the following array:
import numpy as np
arr = np.array([1,2,3,4,5])

print(arr[0])

1


In [2]:
# Get third and fourth elements from the following array and add them.

print(arr[2] + arr[3])

7


### Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [4]:
# Access the element on the first row, second column:

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1])

# Access the element on the 2nd row, 5th column:
print(arr[1,4])

2
10


### Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [7]:
# Access the third element of the second array of the first array:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


### Negative Indexing
Use negative indexing to access an array from the end.

In [11]:
# Print the last element from the 2nd dim:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,-1])

10


### Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [14]:
# Slice elements from index 1 to index 5 from the following array:

arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

# Note: The result includes the start index, but excludes the end index.

[2 3 4 5]


In [15]:
# Slice elements from index 4 to the end of the array:
print(arr[4:])

# Slice elements from the beginning to index 4 (not included):
print(arr[:4])

[5 6 7]
[1 2 3 4]


### Negative Slicing
Use the minus operator to refer to an index from the end:

In [16]:
# Slice from the index 3 from the end to index 1 from the end:
print(arr[-3:-1])

[5 6]


### STEP
Use the step value to determine the step of the slicing:

In [18]:
# Return every other element from index 1 to index 5:
print(arr[1:5:2])

# Return every other element from the entire array:
print(arr[::2])

[2 4]
[1 3 5 7]


### Slicing 2-D Arrays

In [19]:
# From the second element, slice elements from index 1 to index 4 (not included):
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [22]:
# From both elements, return index 2:
print(arr[0:2, 2])

[3 8]


In [23]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]
